<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add a user to the system' => 'Voeg een gebruiker toe aan het systeem',
    'Cannot assign role "{0}" as the AuthManager is not configured in your application' => 'Kan rol "{0}" niet toewijzen aangezien AuthManager niet geconfigureerd is voor jouw applicatie.',
    'Email' => 'Email',
    'Role the user needs to have. If this role doesn\'t exist it will be made' => 'De rol die aan de gebruiker wordt toegewezen. Als de rol niet bestaat wordt deze aangemaakt',
    'User setup' => 'Gebruiker installatie',
    'When empty a password will be generated' => 'Indien leeg zal een paswoord gegenereerd worden',
    'role' => 'Rol',
];
