<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"allow_url_include" should be disabled at php.ini' => '"allow_url_include" wordt best gedisabled in php.ini',
    '"expose_php" should be disabled at php.ini' => '"expose_php" wordt best gedisabled in php.ini',
    'Cannot continue until the requirements are met. Please contact your IT responsible.' => 'De installer kan niet worden vervolgt zolang niet aan deze vereisten werd voldaan. Gelieve de IT verandtwoordelijke te contacteren',
    'Conclusion' => 'Conclusie',
    'Congratulations! Your server configuration satisfies all requirements.' => 'Proficiat! Jouw server voldoet aan alle vereisten.',
    'Details' => 'Details',
    'Failed' => 'Gefaald',
    'Memo' => 'Memo',
    'Name' => 'Name',
    'PHP mail SMTP server required' => 'PHP mail SMTP server is verplicht',
    'PHP version 7.1 required' => 'PHP versie 7.1 is verplicht',
    'Passed' => 'OK',
    'Required By' => 'Vereist door',
    'Required for MySQL database.' => ' Vereist voor de MySQL database.',
    'Required for database connections.' => 'Vereist voor het maken van een database connectie',
    'Result' => 'Resultaat',
    'System Check' => 'Systeem Checker',
    'There are two kinds of requirements being checked. Mandatory requirements are those that have to be met to allow the application to work as expected. <br />
			There are also some optional requirements being checked which will show you a warning when they do not meet. Functionality may not be available when the optional requirements aren\'t met.' => 'Er worden twee soorten vereisten gechecked. Verplichte vereisten die nodig zijn om de applicatie naar behoren te laten werken <br/>
			Er zijn ook een aantal optionele vereisten die een waarschuwing tonen indien niet aan deze voldaan zijn. Sommige functionaliteiten zijn niet beschikbaar indien deze vereisten niet voldaan zijn.',
    'This script checks if your server configuration meets the requirements for running the  application. 
            It checks if the server is running the right version of PHP, if appropriate PHP extensions have been loaded, and if php.ini file settings are correct.' => 'Dit script controleert of de server configuratie voldoet aan de vereisten om de applicatie te draaien. Het controleert de PHP versie, PHP extensies en php.ini settings.',
    'Unfortunately your server configuration does not satisfy the requirements by this application.<br />Please refer to the table below for detailed explanation.' => 'Jouw server voldoet niet aan de vereisten voor deze applicatie.<br />Gelieve de onderstaande tabel te bekijken voor meer details.',
    'Warning' => 'Waarschuwing',
    'Your server configuration satisfies the minimum requirements by this application.<br />Please pay attention to the warnings listed below and check if your application will use the corresponding features.' => 'Jouw server voldoet aan de minim vereisten voor deze applicatie. <br /> Gelelieve de waarschuwingen te bekijken en te controleren of jouw applicatie deze features zal gebruiken.',
];
