<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Congratulations!</strong> You\'re done.' => '<strong>Proficiat!</strong> Je bent klaar.',
    'Application name' => 'Applicatie naam',
    'Go to website' => 'Ga naar website',
    'Please adapt your settings if necessary.' => 'Gelieve de instellingen aan te passen indien nodig.',
    'Settings Configuration' => 'Instellingen',
    'The installation completed successfully! Have fun with {0}.' => 'De installatie is met succes beëindigd! Veel plezier met {0}.',
    'These are the current settings. You can adapt them by clicking on "Edit"' => 'Dit zijn de huidige instellingen. Je kan deze aanpassen door te klikken op "Edit"',
    'Time zone' => 'Tijdzone',
];
