<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Database Configuration' => 'Database Configuratie',
    'Database name' => 'Database naam',
    'Hostname' => 'Host naam',
    'Incorrect configuration' => 'Configuratie ongeldig!',
    'Migration succesfull!' => 'Migratie is gelukt!',
    'Please enter your database connection details. If you’re not sure about these, please contact your administrator or web host.' => 'Gelieve de database gegevens in te vullen. Indien je niet zeker bent, contacteer dan je administrator of web host.',
    'The hostname. You should be able to get this from your hosting or use the default "localhost".' => 'De host naam. Deze kan je krijgen van jouw hosting of je kan de standaard waarde "localhost" proberen.',
    'The name of the database you want to install your application on.' => 'De naam van de database waarin de applicatie wordt geïnstalleerd.',
    'The next step will execute database updates. Do not refresh the page!' => 'De volgende stap voert enkele database updates uit. Gelieve de pagina niet te verversen!',
    'These are the current connection details. If you’re not sure about these, please contact your administrator or web host.' => 'Dit zijn de huidige database gegevens. Indien je niet zeker bent, contacteer dan je administrator of web host.',
];
