<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirm password' => '@@Bevestig wachtwoord@@',
    'Email shown to reply to when sending from the application' => 'Email dat gebruikt wordt op op te antwoorden op mails verzonden via de applicatie',
    'Encryption' => 'Beveiliging',
    'Encryption when sending emails. Ssl or tls are advised.' => 'Beveiliging bij het verzenden van emails. Ssl of tls zijn aangeraden (indien beschikbaar). ',
    'From email address' => 'Verzonden van uit email adres',
    'From name' => 'Verzonden uit naam van',
    'Host' => 'Host',
    'Mailer Configuration' => 'Mailer configuratie',
    'Name shown to the receiver of messages sent via the application' => 'De naam getoond bij het ontvangen van emails vanuit de applicatie',
    'Please enter your mail configuration settings. If you’re not sure about these, please contact your administrator or web host.' => 'Gelieve de email configuratie gegevens in te geven. Indien je niet zeker bent, contacteer dan jouw administrator of web host.',
    'Port' => 'Poort',
    'Port of the mail application' => '@@Poort voor de mail applicatie@@',
    'The mail host' => '@@De mail host@@',
    'These are the current mail details. If you’re not sure about these, please contact your administrator or web host.' => 'Dit zijn de huidige mail instellingen. Indien je niet zeker bent, contacteer dan jouw administrator of web host.',
];
